"""add back columns in trip

Revision ID: 1484b2a6c9bb
Revises: 150d5526fe54
Create Date: 2023-07-23 09:15:39.556793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1484b2a6c9bb'
down_revision = '150d5526fe54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('end_lng')
        batch_op.drop_column('end_lat')
        batch_op.drop_column('start_lng')
        batch_op.drop_column('start_lat')

    # ### end Alembic commands ###
