"""create m2m relationship

Revision ID: 150795efb047
Revises: f1fb5c26e3bd
Create Date: 2023-07-28 08:52:15.072819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150795efb047'
down_revision = 'f1fb5c26e3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trips_subwaystops_id_subwaystops', type_='foreignkey')
        batch_op.drop_column('subwaystops_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subwaystops_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_trips_subwaystops_id_subwaystops', 'subwaystops', ['subwaystops_id'], ['id'])

    # ### end Alembic commands ###
