"""change columns for trip

Revision ID: 150d5526fe54
Revises: 5bf752e4d4c4
Create Date: 2023-07-22 19:43:42.381666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150d5526fe54'
down_revision = '5bf752e4d4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_trips_end_id_subwaystops'), 'subwaystops', ['end_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_trips_start_id_subwaystops'), 'subwaystops', ['start_id'], ['id'])
        batch_op.drop_column('start_lat')
        batch_op.drop_column('end_lat')
        batch_op.drop_column('end_lng')
        batch_op.drop_column('start_lng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('end_lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('end_lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('start_lat', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_trips_start_id_subwaystops'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trips_end_id_subwaystops'), type_='foreignkey')
        batch_op.drop_column('end_id')
        batch_op.drop_column('start_id')

    # ### end Alembic commands ###
