"""add columns to trips


Revision ID: 1c4c6a1fb6d6
Revises: c3a84ab348e0
Create Date: 2023-07-27 14:25:55.608105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4c6a1fb6d6'
down_revision = 'c3a84ab348e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stops_travled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('route', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subwaystopstart_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_trips_start_id_subwaystops', type_='foreignkey')
        batch_op.drop_constraint('fk_trips_end_id_subwaystops', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trips_subwaystopstart_id_subwaystops'), 'subwaystops', ['subwaystopstart_id'], ['id'])
        batch_op.drop_column('end_id')
        batch_op.drop_column('start_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('end_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_trips_subwaystopstart_id_subwaystops'), type_='foreignkey')
        batch_op.create_foreign_key('fk_trips_end_id_subwaystops', 'subwaystops', ['end_id'], ['id'])
        batch_op.create_foreign_key('fk_trips_start_id_subwaystops', 'subwaystops', ['start_id'], ['id'])
        batch_op.drop_column('subwaystopstart_id')
        batch_op.drop_column('route')
        batch_op.drop_column('stops_travled')

    # ### end Alembic commands ###
