"""add columns to Station

Revision ID: 3ae8faee41a4
Revises: 43c52dfe6823
Create Date: 2023-07-18 09:40:03.827325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae8faee41a4'
down_revision = '43c52dfe6823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('routes')

    # ### end Alembic commands ###
