"""get rid of passwords

Revision ID: 57591036bbdf
Revises: c3b73b9fb397
Create Date: 2023-07-31 16:11:49.326877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57591036bbdf'
down_revision = 'c3b73b9fb397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
