"""cleanup trips table

Revision ID: 5dfc9ead2114
Revises: b60005b26acc
Create Date: 2023-07-31 12:16:16.682590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfc9ead2114'
down_revision = 'b60005b26acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('start_lat')
        batch_op.drop_column('forwardDirection')
        batch_op.drop_column('stops_travled')
        batch_op.drop_column('end_lat')
        batch_op.drop_column('route')
        batch_op.drop_column('end_lng')
        batch_op.drop_column('start_lng')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('start_lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('end_lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('route', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('stops_travled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('forwardDirection', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('start_lat', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
