"""create trip table

Revision ID: 66b19db7b424
Revises: 902296ed9f93
Create Date: 2023-07-22 11:38:00.640340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b19db7b424'
down_revision = '902296ed9f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_lat', sa.Integer(), nullable=True),
    sa.Column('start_lng', sa.Integer(), nullable=True),
    sa.Column('end_lat', sa.Integer(), nullable=True),
    sa.Column('end_lng', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
