"""add favorite column to trips

Revision ID: 8e26d5e16d57
Revises: c3b73b9fb397
Create Date: 2023-08-01 11:39:26.299412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e26d5e16d57'
down_revision = 'c3b73b9fb397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isFavorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('isFavorite')

    # ### end Alembic commands ###
