"""add columns to trips

Revision ID: 9b05be0cb4a8
Revises: 1484b2a6c9bb
Create Date: 2023-07-24 08:51:55.835861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b05be0cb4a8'
down_revision = '1484b2a6c9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
