"""back to normal

Revision ID: ae8222acb23a
Revises: 150795efb047
Create Date: 2023-07-28 09:08:31.185459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8222acb23a'
down_revision = '150795efb047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_subwaystop')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subwaystopstart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_trips_subwaystopstart_id_subwaystops'), 'subwaystops', ['subwaystopstart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trips_subwaystopstart_id_subwaystops'), type_='foreignkey')
        batch_op.drop_column('subwaystopstart_id')

    op.create_table('trip_subwaystop',
    sa.Column('trip_id', sa.INTEGER(), nullable=False),
    sa.Column('subwaystop_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subwaystop_id'], ['subwaystops.id'], name='fk_trip_subwaystop_subwaystop_id_subwaystops'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_trip_subwaystop_trip_id_trips'),
    sa.PrimaryKeyConstraint('trip_id', 'subwaystop_id')
    )
    # ### end Alembic commands ###
