"""add a m2m table

Revision ID: f1fb5c26e3bd
Revises: a0fa2f770f3b
Create Date: 2023-07-28 08:49:19.245881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fb5c26e3bd'
down_revision = 'a0fa2f770f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_subwaystop',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('subwaystop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subwaystop_id'], ['subwaystops.id'], name=op.f('fk_trip_subwaystop_subwaystop_id_subwaystops')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_subwaystop_trip_id_trips')),
    sa.PrimaryKeyConstraint('trip_id', 'subwaystop_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_subwaystop')
    # ### end Alembic commands ###
